-- Phase 7: Night Events table
-- Run this in the Supabase SQL editor after schema.sql

-- ── night_events ───────────────────────────────────────────────────────────
-- Stores the resolved event log for each night. Generated by the rule engine
-- and committed when the Storyteller confirms the resolution.

CREATE TABLE IF NOT EXISTS night_events (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id             uuid NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  night_number        int  NOT NULL,
  event_type          text NOT NULL,           -- 'death' | 'protection' | 'poison' | 'transform' | 'info' | 'trigger' | 'advisory'
  description         text NOT NULL,           -- human-readable event text
  affected_player_ids uuid[] NOT NULL DEFAULT '{}',  -- players involved in this event
  created_at          timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS night_events_room_night
  ON night_events (room_id, night_number);

-- RLS
ALTER TABLE night_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "open read night_events"
  ON night_events FOR SELECT USING (true);

CREATE POLICY "open insert night_events"
  ON night_events FOR INSERT WITH CHECK (true);

CREATE POLICY "open delete night_events"
  ON night_events FOR DELETE USING (true);

-- Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE night_events;
